### ISSUE TITLE
Cartographer and Talented

### ISSUE THREAD

**Issue by lishpeth** [ElvUI-TBC/ElvUI_AddOnSkins#1]
Thanks for bringing Elvui AddonSkins into TBC. Can we add some more addon skins like Cartographer or Talented? They are widely used. There is a Skinner addon that skins them standalone. If Elvui could skin them, it would be great. Also I couldn't make Omen to be skinned with Elvui. Embed settings are not working well, too...

**Comment by Crumdidlyumshis** [comment]
Still some bugs to work out, but I will add them to the to-do list and update ya when added :)

**Comment by Crumdidlyumshis** [comment]
@Loaal I have talented 90% completed, but I cannot seem to find the frame for the buttons to be skinned.
