### ISSUE TITLE
Omen and Recount are always hidden on several chars

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI_AddOnSkins#11]
It doesn't matter if i enable/disable embed settings, these 2 addons are always hidden in several chars (occures on warrior and shaman for example). The command /recount toggle or /omen toggle doesn't help. Deactivating the AddonSkins addon solves the problem.

**Comment by fatlus** [comment]
Seems to work after the latest commits.

**Comment by fatlus** [comment]
Happens again, cannot reproduce it. The both embed Windows are suddenly gone

**Comment by fatlus** [comment]
Could you check this issue again? It's the main reason I couldn't use AddonSkins.

**Comment by fatlus** [comment]
No update for this issue? Cant't use AddonSkins because of it.

**Comment by fatlus** [comment]
For clarification: Omen and Recount are working but the embed settings break these two addons.

**Comment by fatlus** [comment]
Any news on this case? Omen and Recount still works with AddonSkins but with disabled embed settings. Turning on embed settings (single or double doesn't matter) breaks the function.

**Comment by Loaal** [comment]
Embed module updated, check if problem still persists.

**Comment by fatlus** [comment]
Works!
