### ISSUE TITLE
Cartographer is not skinned sufficiently

### ISSUE THREAD

**Issue by lishpeth** [ElvUI-TBC/ElvUI_AddOnSkins#16]
Cartographer hasn't been skinned properly yet (you can see the grey places around the world map) and when I try to click the options button for Cartographer I get the error in the screenshots;
![wowscrnshot_072717_100940](https://user-images.githubusercontent.com/28478416/28658420-ec299ae0-72b3-11e7-956a-e18e526c950e.jpg)
![wowscrnshot_072717_101018](https://user-images.githubusercontent.com/28478416/28658425-f127ffc8-72b3-11e7-969c-38d005ff4641.jpg)

**Comment by Loaal** [comment]
What version of your Cartographer?

**Comment by lishpeth** [comment]
It's 2.0.

**Comment by Loaal** [comment]
Use latest version of [Cartographer](https://www.wowace.com/projects/cartographer/files/298196) (2.2)

**Comment by lishpeth** [comment]
I actually download the latest one, but it is not functioning properly like "right-clicking" to zoom out:( 2.0 version was working perfectly but its not skinning like 2.2 version :(

**Comment by Loaal** [comment]
Without knowing revision number of your version it may be for patch 2.0.12.

**Comment by lishpeth** [comment]
Again a ridiculous reason :D I have changed the interface in 2.2 version from 30000 to 20400 and now its perfectly fine :) Thanks for the help

**Comment by lishpeth** [comment]
If its not too much to asked from here, which version of Dbm needs to be used for perfectly skinned with Elvui? Mine is 1.5 and except the option frame of Dbm, bars are unskinned...
