### ISSUE TITLE
LUA Error: BugSack and Fishingbuddy

### ISSUE THREAD

**Issue by fuba82** [ElvUI-TBC/ElvUI_AddOnSkins#18]
Hi there,
I think i use the wrong version of both AddOns.. mabye? :D

BugSack: [BugSack-3.0-beta.zip](https://www.wowace.com/projects/bugsack/files/297385)
FishingBuddy: [Fishing Buddy v0.9.4m](https://wow.curseforge.com/projects/fishingbuddy/files/134920)

Both of them are the last version for 2.4.3 i found.

Maybe you got a List of AddOns you used for the current ElvUI_AddOnSkins to prevent errors?

Edit:
Aha i see there are some Skins from 3,x AddOns like "Enchantrix" from [Auctioneer Suite 5.8.4723](https://wow.curseforge.com/projects/auctioneer/files/427812)
Probably also the BugSack and FishingBuddy is from Newer Version?

**Comment by Crumdidlyumshis** [comment]
is this still relevant?

**Comment by fuba82** [comment]
> is this still relevant?

not really.  
totaly forgot about this... :P  
sorry  
  
i try to fix all the skins i use if it is necessary

**Comment by Crumdidlyumshis** [comment]
no problem! Thank you for the great updates! Keep em coming 😄
