### ISSUE TITLE
Atlasloot

### ISSUE THREAD

**Issue by Larsy93** [ElvUI-TBC/ElvUI_AddOnSkins#2]
Message: Interface\AddOns\ElvUI\modules\skins\skins.lua:49: attempt to index local 'f' (a nil value)
Time: 06/24/17 19:21:41
Count: 1
Stack: (tail call): ?
(tail call): ?
Interface\AddOns\ElvUI\modules\skins\skins.lua:49: in function `HandleButton'
...terface\AddOns\ElvUI_AddOnSkins\addons\atlasLoot.lua:62: in function <...terface\AddOns\ElvUI_AddOnSkins\addons\atlasLoot.lua:4>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
Interface\AddOns\ElvUI\modules\skins\skins.lua:550: in function `Initialize'
Interface\AddOns\ElvUI\modules\skins\skins.lua:584: in function <Interface\AddOns\ElvUI\modules\skins\skins.lua:583>
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:155: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:155>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
Interface\AddOns\ElvUI\core\core.lua:968: in function `InitializeModules'
Interface\AddOns\ElvUI\core\core.lua:1099: in function `?'
...her\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:146: in function <...her\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:146>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...her\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:91: in function `Fire'
...AddOns\ClassTimer\Libs\AceEvent-3.0\AceEvent-3.0.lua:70: in function <...AddOns\ClassTimer\Libs\AceEvent-3.0\AceEvent-3.0.lua:69>

**Comment by Crumdidlyumshis** [comment]
Was on my todo list :) I'll work on it when I get home from work.

**Comment by Crumdidlyumshis** [comment]
fixed 2ea8d5a94271ea5db83ddf37832b1838e72dd881 :)
