### ISSUE TITLE
QuestGuru Error When Picking Up Quest

### ISSUE THREAD

**Issue by Fanquar** [ElvUI-TBC/ElvUI_AddOnSkins#32]
![image](https://user-images.githubusercontent.com/41789276/46248248-6013c380-c417-11e8-81e1-dbb7f54882cf.png)

detailed error:
Message: ...e\AddOns\ElvUI_AddOnSkins\Skins\Addons\questGuru.lua:116: attempt to index local 'questItem' (a nil value)
Time: 09/29/18 18:40:23
Count: 3
Stack: (tail call): ?
[C]: ?
...e\AddOns\ElvUI_AddOnSkins\Skins\Addons\questGuru.lua:116: in function <...e\AddOns\ElvUI_AddOnSkins\Skins\Addons\questGuru.lua:84>
[C]: ?
[C]: ?
[C]: in function `QuestFrameItems_Update'
Interface\FrameXML\QuestFrame.lua:596: in function `QuestFrameDetailPanel_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[C]: in function `Show'
Interface\FrameXML\QuestFrame.lua:38: in function `QuestFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

**Comment by Vitoshka** [comment]
**Same**

Message: ...e\AddOns\ElvUI_AddOnSkins\Skins\Addons\questGuru.lua:116: attempt to index local 'questItem' (a nil value)
Time: 10/24/18 16:23:50
Count: 1
Stack: (tail call): ?
[C]: ?
...e\AddOns\ElvUI_AddOnSkins\Skins\Addons\questGuru.lua:116: in function <...e\AddOns\ElvUI_AddOnSkins\Skins\Addons\questGuru.lua:84>
[C]: ?
[C]: ?
[C]: in function `QuestFrameItems_Update'
Interface\FrameXML\QuestFrame.lua:79: in function `QuestFrameRewardPanel_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[C]: in function `Show'
Interface\FrameXML\QuestFrame.lua:44: in function `QuestFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>
