### ISSUE TITLE
Omen

### ISSUE THREAD

**Issue by Larsy93** [ElvUI-TBC/ElvUI_AddOnSkins#4]
Message: Interface\AddOns\ElvUI_AddOnSkins\addons\omen.lua:7: hooksecurefunc(): UpdateBars is not a function
Time: 06/24/17 19:23:56
Count: 1
Stack: (tail call): ?
(tail call): ?
[C]: in function `hooksecurefunc'
Interface\AddOns\ElvUI_AddOnSkins\addons\omen.lua:7: in function <Interface\AddOns\ElvUI_AddOnSkins\addons\omen.lua:4>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
Interface\AddOns\ElvUI\modules\skins\skins.lua:550: in function `Initialize'
Interface\AddOns\ElvUI\modules\skins\skins.lua:584: in function <Interface\AddOns\ElvUI\modules\skins\skins.lua:583>
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:155: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:155>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
Interface\AddOns\ElvUI\core\core.lua:968: in function `InitializeModules'
Interface\AddOns\ElvUI\core\core.lua:1099: in function `?'
...her\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:146: in function <...her\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:146>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...her\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:91: in function `Fire'
...AddOns\ClassTimer\Libs\AceEvent-3.0\AceEvent-3.0.lua:70: in function <...AddOns\ClassTimer\Libs\AceEvent-3.0\AceEvent-3.0.lua:69>

**Comment by Crumdidlyumshis** [comment]
I will need your help on this @Loaal :)
