### ISSUE TITLE
Problem with ElvUI_AddOnSkins: Postal

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-TBC/ElvUI_AddOnSkins#45]
[Postal](https://www.wowace.com/projects/postal/files/137440) addon skin (**inbox buttons**) not working correctly.
**[Example](https://a.radikal.ru/a24/1811/ea/08ae372174cb.jpg)**

**Comment by Apollyonn** [comment]
![wowscrnshot_110218_212704](https://user-images.githubusercontent.com/19589902/47936429-40742d00-dee6-11e8-870c-162c2c7f8595.jpg)
Works fine for me.

**Comment by Vitoshka** [comment]
I found a problem it turns out there is some kind of [conflict](https://d.radikal.ru/d15/1811/71/91195b4e6b9e.jpg) of an important addon [AtlasLoot](https://www.curseforge.com/wow/addons/atlasloot-enhanced/files?filter-game-version=2020709689%3A41) _v4.06.04-TestBeta_ and skin Postal ElvUi TBC.
Can you fix it?

**Comment by fatlus** [comment]
The three buttons are not skinned properly for me too. Seems to be an Ace2/3 conflict with other addons

**Comment by fatlus** [comment]
Talented skin broken too

**Comment by Arcitec** [comment]
@Apollyonn Perhaps you're using an outdated version of Postal.

Try the latest release for TBC (version "Postal-r82138.1"):

https://www.curseforge.com/wow/addons/postal/files?filter-game-version=2020709689%3A41

I don't see any skinned buttons for it.

**Comment by fatlus** [comment]
Should be fixed with https://github.com/ElvUI-TBC/ElvUI_AddOnSkins/pull/51/commits/d84649acd68cd15900f888466ccb1b1954e808d1
You can try https://github.com/fatlus/ElvUI_AddOnSkins-1 if the pull request isn merged soon.
